steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
options:
  logging: LEGACY
logsBucket: gs://celeryman-os_cloudbuild/logs
serviceAccount: projects/celeryman-os/serviceAccounts/celeryman-builder@celeryman-os.iam.gserviceaccount.com
timeout: 1200s
