// Explicit experiment for every generation request, including print frames.
// No variant or profile may silently fall back to the anchored pipeline.
export function usesTextOnlyDance(body:{canonical?:boolean;variant?:string;fastPath?:boolean}){
 return body.fastPath===true;
}
export function textMotionPrompt(costume:string,motion:string,portrait=false){
 if(portrait)return `Generate the SAME recognizable adult person depicted in Image 1, the original identity photograph. Preserve facial proportions, hair, age appearance, and presence or absence of facial hair and eyeglasses, except eyewear or headwear explicitly specified by the costume. Image 1 supplies identity only: never copy its clothing, scenery, pose or camera framing. Dress the person in this outfit: ${costume}. Reframe as a tight head-and-shoulders portrait, with the entire head and any hat visible with a small margin above, shoulders and upper chest filling the bottom edge. Never show the waist, legs or feet. Solid hot pink studio background, edge to edge. Locked static camera with no zoom. Flat 1990s low-budget desktop footage. Small rhythmic head bobs and glances, subtle awkward smile. Exactly one coherent person, no pasted head, collage, other people, text, cuts or speech. End in the starting pose for a seamless five-second loop.`;
 return `Generate the SAME recognizable adult person depicted in Image 1, the original identity photograph. Preserve facial proportions, hair, age appearance, body build, and presence or absence of facial hair and eyeglasses, except eyewear or headwear explicitly specified by the costume. Any additional still reference depicts this same person already dressed in the requested costume and supplies costume and staging guidance. The original identity photograph supplies identity only: never copy its clothing, scenery, pose or camera framing. Dress the person in this complete outfit: ${costume}. Full body including shoes visible throughout, centered, occupying 80% of frame height, with margins above and below. Flat uniform light gray seamless studio background. Locked static camera, flat 1990s low-budget desktop dance footage. Choreography: ${motion} Exactly one coherent whole person; no pasted head, collage, other people, text, cuts or speech. Start moving immediately, repeat a rhythmic five-second cycle, end in the starting pose without stopping or fading.`;
}
