import {chromium} from 'playwright';import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/voice-lab/index.html');await page.waitForFunction(()=>!!(window as any).voiceLab);const metrics=[];
for(const method of ['classic-Fred','classic-Junior','turbo','hd']){
 const result=await page.evaluate(async method=>await (window as any).voiceLab.run(method,'Good morning Thomas. What will your first sequence of the day be?'),method);metrics.push(result);console.log(method,JSON.stringify(result));await page.waitForTimeout(4500);
}
// Exercise reused production splicing with the benchmark name cache, then the browser's own cache.
await page.fill('#live-text','A sentence that cannot be spliced.');await page.selectOption('#method','splice');await page.click('#generate');await page.waitForFunction(()=>document.querySelector('#live-status')?.textContent?.includes('templates only'));const unsupported=await page.textContent('#live-status');
await page.selectOption('#method','turbo');await page.fill('#live-text','Thomas, your velvet turnip shuffle is ready. Shall I add a tiny purple hat?');await page.click('#generate');await page.waitForTimeout(200);await page.click('#stop');await page.waitForTimeout(1000);const stopped=await page.textContent('#live-status');
await page.selectOption('#case','greeting-thomas');const hidden=await page.locator('.candidate .reveal:not(.hidden)').count()===0;await page.locator('.candidate select').first().selectOption('4');await page.locator('.candidate textarea').first().fill('Listening test saved.');await page.locator('.candidate textarea').first().blur();await page.click('#reveal');const revealed=await page.locator('.candidate .reveal:not(.hidden)').count()>0;await page.screenshot({path:'benchmarks/voice-lab/listening-page.png',fullPage:true});
const report={created:new Date().toISOString(),metrics,checks:{streamedAudibleBeforeComplete:metrics.filter(m=>['turbo','hd'].includes(m.method)).every(m=>m.firstAudibleMs!==null&&m.firstAudibleMs<m.completeMs),classicAudible:metrics.filter(m=>m.method.startsWith('classic')).every(m=>m.firstAudibleMs!==null),unsupportedSpliceExplained:unsupported?.includes('templates only'),cancellation:stopped==='Stopped.',blindByDefault:hidden,revealWorks:revealed,noBrowserErrors:errors.length===0},errors};
await fs.writeFile('benchmarks/voice-lab/browser-tests.json',JSON.stringify(report,null,2));await fs.writeFile('public/voice-lab/browser-tests.json',JSON.stringify(report,null,2));console.log(report.checks);await browser.close();if(Object.values(report.checks).some(v=>!v))process.exitCode=1;
