import 'dotenv/config';import fs from 'node:fs/promises';import {fal} from '@fal-ai/client';
fal.config({credentials:process.env.FAL_KEY});
const jobs=[{name:'oyster',id:'8b3274bb50a1c5b384f5',pose:'The performer is bent deeply forward from the waist, feet spread wide, both hands held near the thighs. His red-and-black flame beanie is airborne twenty centimeters directly above his head, revealing the same short dark hair. The hat is visibly detached, with a clear gap between hat and head. Keep the full body, red hoodie, black pants with red flame graphics, pale yellow/cyan backdrop and exact fixed camera unchanged.',time:2},{name:'hat',id:'d6ff076568741cd0d5bb',pose:'Keep the head and shoulders perfectly upright and still. Tilt the BLACK FEDORA itself 30 degrees toward the viewer left, balanced comically on the head. The face, neck, shoulders, black sunglasses, gold patterned shirt and hot pink background remain in exactly their positions. Tight head-and-shoulders portrait. Whole image regenerated coherently, no pasted layers.',time:2.5}];
await Promise.all(jobs.map(async j=>{
 const start=await fal.storage.upload(new File([await fs.readFile(`public/media/generated/${j.id}.png`)],'start.png',{type:'image/png'}));
 const frame=await fal.subscribe('fal-ai/nano-banana-2/edit',{input:{image_urls:[start],prompt:'Generate the next keyframe of this coherent live-action performance. Same adult person, costume, anatomy, camera and studio lighting. '+j.pose,aspect_ratio:j.name==='hat'?'4:3':'4:3',resolution:'1K',output_format:'png'}});
 const middle=frame.data.images[0].url;await fs.writeFile(`analysis/${j.name}-middle.png`,Buffer.from(await(await fetch(middle)).arrayBuffer()));
 const ref=await fal.storage.upload(new File([await fs.readFile(`public/media/motion/${j.name}-5s.mp4`)],'motion.mp4',{type:'video/mp4'}));
 const prompt=j.name==='oyster'?'Same whole person performs exactly the fast alternating bow-and-rise dance in Video 1, on each beat, 8 fast bows in 5 seconds. Stand up between every bow and let fists separate to either side of the hips. At two seconds the flame hat flies up off the head as in the middle keyframe, then lands back on the head. Follow the full reference choreography, including arm positions and hat flight. No camera movement. Entire person generated naturally together.':'Same whole person performs the hat wobble in Video 1. The black fedora tilts left and right comically while the head and shoulders stay almost still. Three wobble cycles in five seconds. Smile broadly and look at the camera. Keep hot pink studio background. Entire portrait generated naturally together.';
 const result=await fal.subscribe('minimax/h3-max/reference-to-video',{input:{image_url:start,middle_image_url:middle,middle_frame_time:j.time,end_image_url:start,reference_video_urls:[ref],prompt,duration:5,resolution:'480P',prompt_expansion_mode:'disabled'}});
 await fs.writeFile(`analysis/${j.name}-keyframes.mp4`,Buffer.from(await(await fetch(result.data.video.url)).arrayBuffer()));console.log(j.name,'complete');
}));
